// export const initialState = {
//   allPets: [
//     {
//       name: "Drogo",
//       image:
//         "https://www.phototoutou.com/photos/a2599n1-aiko-berger-allemand-croise-husky.jpg",
//       type: "Dog",
//       breed: "Huskey",
//       birthDate: "2017-02",
//       vaccinated: "Yes",
//       petId: "p1",
//       userId: "60aa860539cc640ac44fe14e",
//       gender: "Male",
//     },
//     {
//       name: "Lili",
//       image:
//         "https://www.zooplus.fr/magazine/wp-content/uploads/2018/09/Jack-Russell-gl%C3%BCcklich-1024x684.jpg",
//       type: "Dog",
//       breed: "Jack Russel",
//       birthDate: "2018-9",
//       vaccinated: "Yes",
//       petId: "p2",
//       userId: "60aa860539cc640ac44fe14e",
//       gender: "Female",
//     },
    // {
    //   name: "Vickie",
    //   image:
    //     "https://t1.ea.ltmcdn.com/fr/images/6/2/7/le_bichon_maltais_2726_0_600.jpg",
    //   type: "Dog",
    //   breed: "Bichon",
    //   birthDate: "2013-3",
    //   vaccinated: "Yes",
    //   petId: "p3",
    //   userId: "60aa860539cc640ac44fe14e",
    //   gender: "Female",
    // },
//     {
//       name: "Vanille",
//       image:
//         "https://upload.wikimedia.org/wikipedia/commons/0/06/Chat_persan_beige.jpg",
//       type: "Cat",
//       breed: "Persan",
//       birthDate: "2017-9",
//       vaccinated: "Yes",
//       petId: "p4",
//       userId: "60aa860539cc640ac44fe14e",
//       gender: "Female",
//     },
//     {
//       name: "Danska",
//       image: "https://lactualite.com/assets/uploads/2016/05/pitbull-large.jpg",
//       type: "Dog",
//       breed: "Pitbull",
//       birthDate: "2015-1",
//       vaccinated: "Yes",
//       petId: "p5",
//       userId: "60aa860539cc640ac44fe14e",
//       gender: "Female",
//     },
//     {
//       name: "Blanca",
//       image:
//         "https://www.noovomoi.ca/content/dam/style-de-vie/migrated/images/2016/06/11/chat-persant.png",
//       type: "Cat",
//       breed: "Persan",
//       birthDate: "2016-7",
//       vaccinated: "Yes",
//       petId: "p6",
//       userId: "60aa860539cc640ac44fe14e",
//       gender: "Female",
//     },
//     {
//       name: "Pinky Pete",
//       image:
//         "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/50901197/3/?bust=1620365494&width=1080",
//       type: "Dog",
//       breed: "Labrador Retriever",
//       birthDate: "2016-7",
//       vaccinated: "Yes",
//       petId: "p7",
//       userId: "60aa860539cc640ac44fe14e",
//       gender: "Male",
//     },
//     {
//       name: "Sid",
//       image:
//         "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51447734/1/?bust=1620309922&width=1080",
//       type: "Dog",
//       breed: " Cattle Dog",
//       birthDate: "2016-7",
//       vaccinated: "Yes",
//       petId: "p8",
//       userId: "60aa860539cc640ac44fe14e",
//       gender: "Male",
//     },
//     {
//       name: "Peggy",
//       image:
//         "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/49954564/1/?bust=1620256660&width=1080",
//       type: "Dog",
//       breed: "American Staffordshire Terrier",
//       birthDate: "2016-7",
//       vaccinated: "Yes",
//       petId: "p9",
//       userId: "60aa860539cc640ac44fe14e",
//       gender: "Female",
//     },
//     {
//       name: "Rosamund",
//       image:
//         "https://upload.wikimedia.org/wikipedia/commons/c/c7/Tabby_cat_with_blue_eyes-3336579.jpg",
//       type: "Cat",
//       breed: " Domestic Short Hair ",
//       birthDate: "2021-1",
//       vaccinated: "Yes",
//       petId: "p10",
//       userId: "60aa860539cc640ac44fe14e",
//       gender: "Male",
//     },
//   ],

//   users: [
//     {
//       name: "Syrine",
//       email: "syrinejoulak@gmail.com",
//       password: "123456",
//       phoneNumber: "54675583",
//       city: "Tunis",
//       zipCode: "2092",
//       favoritePets: [
//         {
//           name: "Blanca",
//           image:
//             "https://www.noovomoi.ca/content/dam/style-de-vie/migrated/images/2016/06/11/chat-persant.png",
//           type: "Cat",
//           breed: "Persan",
//           birthDate: "2016-7",
//           vaccinated: true,
//           petId: "p6",
//           userId: "u3",
//           gender: "Female",
//         },
//         {
//           name: "Drogo",
//           image:
//             "https://www.phototoutou.com/photos/a2599n1-aiko-berger-allemand-croise-husky.jpg",
//           type: "Dog",
//           breed: "Huskey",
//           birthDate: "2017-02",
//           vaccinated: true,
//           petId: "p1",
//           userId: "u1",
//           gender: "Male",
//         },
//         {
//           name: "Lili",
//           image:
//             "https://www.zooplus.fr/magazine/wp-content/uploads/2018/09/Jack-Russell-gl%C3%BCcklich-1024x684.jpg",
//           type: "Dog",
//           breed: "Jack Russel",
//           birthDate: "2018-9",
//           vaccinated: true,
//           petId: "p2",
//           userId: "u2",
//           gender: "Female",
//         },
//       ],
//       userId: "u1",
//     },
//     {
//       name: "Nadia",
//       email: "nadiabouhamed@yahoo.fr",
//       password: "123456",
//       phoneNumber: "53675580",
//       city: "Tunis",
//       zipCode: "1004",
//       favoritePets: [],
//       userId: "u2",
//     },
//     {
//       name: "Salwa",
//       email: "salwa32@gmail.com",
//       password: "123456",
//       phoneNumber: "21675583",
//       city: "Tunis",
//       zipCode: "1004",
//       favoritePets: [],
//       userId: "u3",
//     },
//     {
//       name: "Hatem",
//       email: "hatemajmi@yahoo.fr",
//       password: "123456",
//       phoneNumber: "21675584",
//       city: "Tunis",
//       zipCode: "1013",
//       favoritePets: [],
//       userId: "u4",
//     },
//   ],
// };
